In [1]:
import numpy as np

1. Начните писать дневник
2. Задайте последовательность натуральных чисел от 1 до  10
3. Задайте последовательность натуральных чисел от 3 до 33, которые без остатка делятся на 3
4. Задайте последовательность от 5 до -5 в обратном порядке
5. Задайте последовательность 6, 6.1, 6.3 (повторить 4 раза)
6. Задайте последовательность 1,2,...,10,9,8,....,1

In [8]:
x2 = np.arange(start=1, stop=11)
x2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
x3 = np.arange(start=3, stop=36, step=3)
x3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

Повторяем вектор целиком 4 раза:

In [15]:
x5 = np.tile([6, 6.1, 6.3], reps=4)
x5

array([ 6. ,  6.1,  6.3,  6. ,  6.1,  6.3,  6. ,  6.1,  6.3,  6. ,  6.1,
        6.3])

Для сравнения! С помощью `np.repeat` можно повторить каждый элемент:

In [17]:
x5b = np.repeat([6, 6.1, 6.3], repeats=4)
x5b

array([ 6. ,  6. ,  6. ,  6. ,  6.1,  6.1,  6.1,  6.1,  6.3,  6.3,  6.3,
        6.3])

In [29]:
x6 = np.concatenate([np.arange(1, 11), np.arange(start=9, stop=0, step=-1)])
x6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1])